apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dop-local
resources:
  - ../../base
  - ../../services/postgres
  - ../../services/nats
  - ../../emulators/firebase
labels:
  - pairs:
      app.kubernetes.io/part-of: dop
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
